Apply lora with --apply-lora <path-to-safetensors>
filipstrand/mflux pull request #30
Opened 2024-09-03 02:01 UTC by elitexp

**Add --apply-lora Argument for Applying LoRA Weights from Safetensors**

This pull request introduces a new command-line argument, --apply-lora, which allows users to apply Low-Rank Adaptation (**LoRA**) weights from a safetensors file to the model. This enhancement facilitates fine-tuning or adapting existing models using pre-trained LoRA weights.

**Key Files Affected:**

1. src/flux_1/flux.py
2. src/flux_1/weights/weight_handler.py

**Motivation:**
This feature is useful for users who want to quickly adapt pre-trained models with minimal computational overhead, leveraging the flexibility of LoRA. The addition of the safetensors support ensures efficient storage and loading of these specialized weights. Here, I used the weight tensors from [Fal.ai](https://fal.ai)

**Notes:**
Ensure that the safetensors file provided is compatible with the model's architecture and that the LoRA keys correctly map to the model's layers.

2024-09-03 07:15 UTC, anthonywu commented
I'm just a visitor to @filipstrand's repo, and I'm reviewing as an outside observer.

1. 👏🏼  This is an obvious and must-have addition, thanks @elitexp for pursuing this todo item
2. ✅ I ran this on a M1 Max 64GB, I can verify that the PR's `main.py` and the new flags works as advertised
4. ✅ `--apply-lora` on a `*.safetensors` file that I trained with https://github.com/ostris/ai-toolkit works as advertised
5. :question: community playground [lucataco/ai-toolkit/train](https://replicate.com/lucataco/ai-toolkit/train)'s output is based on the same `ostris/ai-toolkit` repo, so I think safe to assume it should work
6. ❓ `safetensor` files trained and distributed by [fal-ai/flux-lora-fast-training](https://fal.ai/models/fal-ai/flux-lora-fast-training/playground) needs verification (I don't have a trained lora ready to go)
7. 🧼 the PR diff needs to be linted/formatted (`ruff`, `black`?) to conform to existing repo standards, this approval should be deferred to maintainer @filipstrand

I have the workflow doing well on my M1 Max, will report back if I find any blockers.

2024-09-03 07:16 UTC, anthonywu requested changes

2024-09-03 07:33 UTC, elitexp commented
Sorry, I mistakenly pushed that import, I was tinkering with the safetensor file to have the proper view of the safetensor file. Thank you for pointing out.
Pushed by removing that import.

2024-09-03 08:59 UTC, sanjok1988 commented
This is a great addition to the project! The introduction of the --apply-lora argument adds significant flexibility by allowing users to easily fine-tune or adapt models using LoRA weights from safetensors. This feature is especially beneficial for those looking to adapt pre-trained models with minimal computational overhead, and the safetensors integration ensures efficient handling of the weights.

Positives:

	•	The implementation seems well thought out, focusing on user needs for quick adaptation of models.
	•	Supporting LoRA through safetensors is a smart choice for efficient storage and loading.
	•	Clear motivation and documentation on the changes, which will help other contributors and users understand the new feature.

Suggestions:

	•	It might be helpful to add a few example commands in the documentation or comments showing how to use the --apply-lora argument effectively.
	•	Consider including some validation checks or warnings for potential mismatches between the LoRA weights and the model architecture, as this could improve user experience and prevent errors.
	•	A small section on troubleshooting common issues related to applying LoRA weights would also be beneficial.

Overall, this PR is a valuable enhancement and aligns well with the needs of the community. Great job!

2024-09-03 09:44 UTC, sandrop8 commented
Great initiative. One idea for further improvement would be to be able to apply multiple LoRA's with that argument? e.g. one style LoRA and one character LoRA.

2024-09-03 10:43 UTC, elitexp commented
I also am a noob on this and am willing to look into loading multiple LoRAs for adjustment.

2024-09-03 11:11 UTC, elitexp commented
Anyone noticed that GPU is not fully utilized during inference??

2024-09-03 11:33 UTC, Xuzzo reviewed
Thanks a lot for your contribution. I find this a very neat and concise way to include LoRAs at inference. I have added a couple of minor points regarding code below.
More importantly, I am comparing the results from here to those from huggingface (using same initial latents) and I am obtaining quite different results. For example, using ["Norod78/Flux_1_Dev_LoRA_Paper-Cutout-Style"](https://huggingface.co/Norod78/Flux_1_Dev_LoRA_Paper-Cutout-Style) with prompt "Gal Gadot as wonderwoman, Paper Cutout Style" I get:
Diffusers
![image (11)](https://github.com/user-attachments/assets/940a5bc0-7c5f-4516-837e-1f32a76e28a0)
Mflux:
![image(8)](https://github.com/user-attachments/assets/0573040d-0e1d-44fb-b2a1-8899cab9fba3)
Model is "dev" and I am using 10 steps, with guidance 3.5, height 256 and width 512

2024-09-03 11:33 UTC, Xuzzo commented on src/flux_1/weights/weight_handler.py
> +        return super(NumpyEncoder, self).default(obj)
This seems to be never used

2024-09-03 11:33 UTC, Xuzzo commented on src/flux_1/weights/weight_handler.py
> +        weights.extend(weight)
```suggestion
        quantization_level = safe_open(lora_path, framework="pt").metadata().get("quantization_level")
        weights = list(mx.load(str(lora_path)).items())
```

2024-09-03 13:12 UTC, sandrop8 commented
It would be great to add in the documentation what this would exactly mean?

"Notes:
Ensure that the safetensors file provided is compatible with the model's architecture and that the LoRA keys correctly map to the model's layers."

E.g. some people train on ostris, some on fal, some use dev LoRA's on schnell. Some use Rank 16,32, 64 when training ostris. So maybe we could add the exact LoRA requirements that would match here?

As I am also not so experienced with that topic, maybe someone could figure out? I am happy to test different LoRA's

2024-09-03 13:27 UTC, sandrop8 commented
![Bildschirmfoto 2024-09-03 um 15 23 27](https://github.com/user-attachments/assets/548bcbc7-9adc-4b47-b7bc-ba63e2953964)

For example I trained a style LoRA on Ostris with rank / linear 32 / 32 on SCHNELL Toolkit and you see the output of the prompt of the image right at step 4750. 

I used the same prompt now and the same seed and sample steps like this " python main.py --model schnell --prompt "a woman holding a coffee cup, in a beanie, sitting at a cafe" --steps 4 --seed 42 --apply-lora style_4750.safetensors"

But the image on the left seem to not even incorporate the LoRA? Am I doing something wrong? Here is the full training config:

![Bildschirmfoto 2024-09-03 um 15 02 26](https://github.com/user-attachments/assets/a8575584-cac1-4450-9e11-1c1f17a53cb4)

2024-09-03 13:53 UTC, elitexp commented
![image(19)](https://github.com/user-attachments/assets/870f9636-ef96-45fd-8152-74397018b4ee)
python main.py --prompt "A girl as a wonderwoman, Paper cutout Style" --apply-lora girl.safetensors paper-cutout.safetensors --lora-scales 1.0 1.0
Can skip 1.0 weights

2024-09-03 14:40 UTC, filipstrand commented
@elitexp Thanks for the contribution! Along with actual fine-tuning, this is a very prioritised feature that @awni also recently asked about, so this is very much appreciated. Will take a look soon when I have the time, but some quick notes:

Regarding not using GPU fully, could it be memory related? : https://github.com/filipstrand/mflux/issues/25

@anthonywu @Xuzzo Thanks for the review efforts, also much appreciated :)

As @Xuzzo mentioned earlier, one important guideline I set for myself when starting this project was to mimic the output from the Diffusers reference implementation as closely as possible (the implementation itself can of course be different / more streamlined / less general etc, if it makes sense). If there are big differences in the output image between Diffusers and MFLUX with the same LoRA weights, then that is definitley worth investigating.

2024-09-03 14:51 UTC, awni commented
This is super cool!! Nice addition @elitexp, hope we can merge it soon. Let me know if there is anything I can do to help.

2024-09-03 14:56 UTC, awni commented on src/flux_1/weights/weight_handler.py
> +        quantization_level = safe_open(lora_file, framework="pt").metadata().get("quantization_level")
You don't need to use `safe_open` fwiw. MLX can read safetensors directly with `mx.load`. And if you want to get the metadata.. just pass `return_metadata=True`. [Here's the docs](https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.core.load.html#mlx.core.load)

2024-09-03 15:08 UTC, awni commented on src/flux_1/weights/weight_handler.py
> +    def _apply_transformer(self,transformer,lora_transformer,lora_scale):
It might be possible to replace most of this with a simpler call to [`mx.utils.tree_map`](https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.utils.tree_map.html#mlx.utils.tree_map). I don't quite follow the logic.. but I think it's recursively descending the matching trees. You would need to pass `lora_transformer` first possible with a custom `is_leaf`. You might need [`tree_map_with_path`](https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.utils.tree_map_with_path.html)


Another alternative entirely is to have a LoRA layer which handles this. That would make more sense if you plan to extend this to training. You can see [how we do it in MLX LM](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/tuner/lora.py).

2024-09-03 21:12 UTC, Xuzzo commented on src/flux_1/weights/weight_handler.py
> +                        continue
The problem seems to be that some weights are not loaded at all. Notice that in the _transformer method some layers names are changed. So in the tree there are no matching keys for them and they get discarded with this `continue` statement. So we need to add some logic that changes the tree keys from huggingface to accommodate this.
More generally, if weights are ignored this should probably not fail silently. I would raise an error here every time it happens. The logic of descending the tree and matching weights should also probably be a bit more explicit, maybe through a separate class where all this is handled (as pointed out above by @awni)

2024-09-04 10:31 UTC, filipstrand commented
@elitexp Just got a chance to try it out with "The_Hound" from @TheLastBen that I randomly found on twitter:

https://huggingface.co/TheLastBen/The_Hound

With LORA:
```
python main.py --prompt "sandor clegane" --model schnell --steps 4 --seed 43 -q 8 --apply-lora "/Users/filipstrand/Desktop/sandor_clegane_single_layer.safetensors" --lora-scales 1.0 
```
![image](https://github.com/user-attachments/assets/45096091-a06b-4a08-9659-798f06ede3fe)

Without LORA:
```
python main.py --prompt "sandor clegane" --model schnell --steps 4 --seed 43 -q 8
```
![image(1)](https://github.com/user-attachments/assets/42b1b0e5-ac33-4fc7-84f0-aebb410431a4)

With LORA (dev):
```
python main.py --prompt "sandor clegane" --model dev --steps 4 --seed 43 -q 8 --apply-lora "/Users/filipstrand/Desktop/sandor_clegane_single_layer.safetensors" --lora-scales 1.0 
```
![image(2)](https://github.com/user-attachments/assets/c4e9ea60-300d-4629-857a-7541b7311c04)

Honestly, I was not expecting it to work "out of the box" with both "schnell" and "dev", but maybe this is actually expected? Anyway really cool that it does!!

This LoRA is ~600kb and seems to perturb only one single transformer block. Just really impressive what can be done with small weight updates!

2024-09-04 13:10 UTC, filipstrand commented on src/flux_1/weights/weight_handler.py
> +                        continue
Nice catch! I can say that this was also a common source of error when developing the project - thinking that weights were loaded when, in fact, they were not. Totally agree with @Xuzzo here, that we should be very explicit when weights are not being set. We should probably also have the same behaviour when loading the original weights just to be sure (in a future PR). Quickly digging around a bit, it might actually be better to use the `load_weights` method which has a `strict` option rather than what I currently did with `update`.  

Also, regarding the weight pre-processing to convert from Diffusers weights to MFLUX weights, while the transformations are not that big, it is a bit unfortunate to also have to think about them here too. 
For now, I think we could reuse that logic as @Xuzzo suggests if it is needed to make sure all LoRA weights are correctly set. Longer term, I can imagine that with some restructuring of the model setup, we can shorten/remove some of the weight transformations (i.e be more similar to the Diffusers layout), but this is more of a "nice to have" thing...

2024-09-04 15:06 UTC, Xuzzo requested changes
With the modifications suggested below I was able to get very similar results between diffusers and mflux. Here an example:
Diffusers:
![fimage](https://github.com/user-attachments/assets/438b7830-b7cc-4a69-8d40-911bfeaf3ff2)
Mflux
![image(17)](https://github.com/user-attachments/assets/5d597d83-f5bc-4dc1-a394-fee41173c408)
Since it would be nice to have this in main asap, I think we could merge this quickly and then iterate in follow-up PRs on making the code more explicit and allowing training LoRAs. What do you think @filipstrand ?

2024-09-04 16:58 UTC, filipstrand commented on src/flux_1/weights/weight_handler.py
> +                        continue
@Xuzzo Great! Now that your changes seem to fix the difference, let's be pragmatic and merge this. I will try to do so later today. Once again, thank you very much.

On another note, I managed to contact the old owner of the previous 'mflux' pip project, and he was kind enough to give it to this project, so after this lora feature is merged, next thing up is to do a proper release and accompany it with some updated documentation.

2024-09-04 18:35 UTC, filipstrand commented
I am doing some refactoring on this branch and am looking at the interface, specifically the fact that `--apply-lora` and `--lora-scales` support loading multiple loras at one. I have personally not tried this yet, does this work well? Does anyone have any examples of a successful fuse of multiple LoRAs? Quite some time ago I remember reading about [ZipLoRA](https://ziplora.github.io), but that method was way more fancy and if I remember correctly, needed to be optimised/trained to actually get the resulting weights. 

It is of course flexible to have the option to support multiple LoRAs, but if it is not commonly used or hard to get to work, we should think about if we really want to support it from the start. Once the interface is publicly available, it may be hard to remove/change if people start building upon it...

2024-09-04 19:53 UTC, sandrop8 commented
Fal.ai is supporting it (at least on dev). Therefore I could test it against our solution. Will update progress in a few hours.

2024-09-04 20:56 UTC, filipstrand commented
@Xuzzo If I can ask you for a favour: I have made some internal refactoring, would it be possible for you to re-run your diffusers vs mflux comparison and confirm their equivalence with the latest commits on this branch when you have the time?

2024-09-04 21:08 UTC, Xuzzo reviewed
Images still match for me. Left a couple of minor comments

2024-09-04 21:08 UTC, Xuzzo commented on src/flux_1/flux.py
> +            lora_scale: str | None = None,
```suggestion
            lora_scale: float = 1.0,
```

2024-09-04 21:12 UTC, filipstrand commented
> Fal.ai supports multiple LoRAs (at least on dev). Therefore I could test it against our solution. Will update progress in a few hours.

Thanks for testing this. Because of simplicity, I think we will go with a single LoRA to begin with. Then we might do an internal rewrite that also supports actual training as discussed above. But it is still interesting to see what use-cases for multiple loras there are and how well that works in practice, so please post any examples you find :) 

Also, since I made some changes, you will have to revert back a few commits to get back the behaviour of multiple LoRAs.

2024-09-04 21:13 UTC, filipstrand commented on README.md
> +- **`--lora-scales`** (optional, `[float]`, default: `[1.0]`): [Scaling factor for each LoRA files]
Thanks, forgot the readme!

2024-09-04 21:18 UTC, filipstrand commented
> Images still match for me. So everything is working well. Left a couple of minor comments

Thanks for checking! I have to setup lora on diffusers myself when I have the time :) 

Then I think this is pretty much ready to be merged. I think it would be nice to add a small section to the readme about this feature also, will do that tomorrow!

2024-09-04 21:48 UTC, sandrop8 commented
> > Fal.ai supports multiple LoRAs (at least on dev). Therefore I could test it against our solution. Will update progress in a few hours.
> 
> Thanks for testing this. Because of simplicity, I think we will go with a single LoRA to begin with. Then we might do an internal rewrite that also supports actual training as discussed above. But it is still interesting to see what use-cases for multiple loras there are and how well that works in practice, so please post any examples you find :)
> 
> Also, since I made some changes, you will have to revert back a few commits to get back the behaviour of multiple LoRAs.

Using multiple LoRAs is pretty common. You can find many examples on civitai. Especially with different lora-scales to just add that extra effect you're looking for. For example here with SDXL:
 Bildschirmfoto 2024-09-04 um 23.34.03
 
For our use case I compared this prompt in fal.ai with our solution:

```python
python main.py --prompt 'sandor clegane, Paper Cutout Style' --model dev --steps 20 --seed 43 --apply-lora sandor.safetensors paper.safetensors --lora-scales 1.0 1.0
```

It's different, but the right direction:
MFLUX:
![image(15)](https://github.com/user-attachments/assets/35b59b5a-7371-4182-8b7c-ad107f5fe584)

FAL.AI:
![Bildschirmfoto 2024-09-04 um 23 17 19](https://github.com/user-attachments/assets/cd9f2939-66a9-430a-a8c0-51afb729d31d)


Second example:
```python
python main.py --prompt 'sandor clegane in a forest, Paper Cutout Style' --model dev --steps 20 --seed 43 --apply-lora sandor.safetensors paper.safetensors --lora-scales 1.0 1.0
```

MFLUX:
![image(17)](https://github.com/user-attachments/assets/c030082a-fd65-47aa-adf9-94132effea37)

FAL.AI:
![Bildschirmfoto 2024-09-04 um 23 26 47](https://github.com/user-attachments/assets/e5334ac4-1744-46ff-a45a-f26be25ad543)

2024-09-05 06:23 UTC, filipstrand commented
@sandrop8 Alright, you have changed my mind :) This seems to be a common thing and especially your second example looks as one would expect. When I have the time after work today, I'll change back to support multiple adapters then we'll try to merge this to main later today. Is it OK if I use your example here of multiple LoRAs in the readme?

2024-09-05 06:31 UTC, elitexp commented
I have also provided thre multiple lora in the above example. Seems to work but hard to get desired. I will also try to read more on documentation of MLX .

2024-09-05 08:08 UTC, sandrop8 commented
Desired output will be easier once we add support for different lora scales like 0.4, 1.2 etc. This is supported in diffusers and fal.ai goes from 0.0 to 4.0 in 0.1 steps - I just used 1.0 because it was supported, but tried other on fal that looked promising.

However if this is not easy for this merge to implement, we could also do it afterwards.

2024-09-05 08:09 UTC, sandrop8 commented
> @sandrop8 Alright, you have changed my mind :) This seems to be a common thing and especially your second example looks as one would expect. When I have the time after work today, I'll change back to support multiple adapters then we'll try to merge this to main later today. Is it OK if I use your example here of multiple LoRAs in the readme?

Sure, you can. And once implemented I would love to share diffusers versus our output instead of fal.ai so we can iterate further on if needed.

2024-09-05 21:28 UTC, merged

2024-09-06 07:52 UTC, filipstrand commented
I want to thank everyone who contributed to this PR and with all the testing and provided examples. I merged this late yesterday with only one small change to the interface: I renamed `--apply-lora` to `--lora-paths`. Other than that it should look the same as earlier.

The next big feature to support is the actual training part. This will involve some internal changes, and we will have to rework how we express the LoRA layers as actual nn modules. 

Also, as I wrote in one comment somewhere, I was lucky to get the `mflux` PyPi name from a previous owner, so during the upcoming weekend my priority will be to do a more proper release of the project. 

Really great job everyone! And if you find something broken, unintuitive or something else, please reach out!

2024-09-06 11:13 UTC, elitexp commented
Thanks to all the reviewer and suggestions. This repo has really made me research more on the MLX library as well and extend my knowledge. Thanks @filipstrand , @anthonywu, @sandrop8 . Really appreciate the time given for the testing and reviews.