Implement Gradio Web UI for MFLUX
filipstrand/mflux pull request #64
Opened 2024-09-23 20:04 UTC by CharafChnioune

This PR introduces a graphical user interface (GUI) for MFLUX using Gradio. The new interface provides an easy-to-use way for users to interact with MFLUX's features without relying on command-line operations.

## Changes

### 1. New Web UI Implementation (`src/mflux/ui/gradio/webui.py`)

- Created a new Gradio-based interface that includes:
  - Tabs for different functionalities (Generate, ControlNet, Quantize Model)
  - Input fields for various parameters (prompt, model, seed, dimensions, etc.)
  - Support for LoRA adapters
  - ControlNet integration
  - Model quantization options

### 2. Updated `README.md`

- Added a new section "🖥️ Using the Graphical User Interface" with instructions on how to use the new `mflux-webui` command
- Updated the installation and usage instructions to include the new GUI option

### 3. Modified `pyproject.toml`

- Added a new entry point for the web UI: `mflux-webui = "mflux.ui.gradio.webui:main"`
- Included Gradio as a new dependency: `"gradio>=4.44.0,<5.0"`

## New Features

- Users can now launch a web-based interface using the `mflux-webui` command
- The GUI provides access to all major MFLUX features, including:
  - Image generation with different models
  - LoRA adapter application
  - ControlNet guided image generation
  - Model quantization and saving

## Testing

The new GUI has been tested locally and appears to provide complete coverage of MFLUX's parameters and functionalities. However, further testing across different environments and use cases is recommended.

## Notes

- The GUI is designed to be intuitive, but we may want to consider adding tooltips or help text for some of the more advanced options in the future.
- We should monitor user feedback on the GUI to identify any areas for improvement or additional features that users might request.

## Screenshots

<img width="1864" alt="Scherm­afbeelding 2024-09-23 om 22 01 56" src="https://github.com/user-attachments/assets/18442f91-13c5-4808-ac8b-7acb0cecdc8f">

<img width="1082" alt="Scherm­afbeelding 2024-09-23 om 22 02 48" src="https://github.com/user-attachments/assets/31b606ce-ae69-4b6c-a626-747ec49825b1">

<img width="1852" alt="Scherm­afbeelding 2024-09-23 om 22 03 17" src="https://github.com/user-attachments/assets/f568e273-c050-46c1-9b9f-5a94dc25ccdc">
<img width="1802" alt="Scherm­afbeelding 2024-09-23 om 22 03 30" src="https://github.com/user-attachments/assets/056a949a-d81d-4374-853d-9c75bb9b7eb6">

2024-09-23 21:26 UTC, anthonywu requested changes
Leaving quick review for now, I will clone the branch and try out the UI next. Thanks @CharafChnioune for getting this effort in here, I think with some care on namespacing/configs/install-scope I can +1 this to be included in the official repo.

For @filipstrand - another consideration is that these frontend files can be stubs, so hypothetically this repo can create all the stubbed files and executable entry points and interfaces, but ultimately in `webui.py` we just `from mflux_gradio import *` where `mflux_gradio` is the external but officially integrated "plugin".

2024-09-23 21:26 UTC, anthonywu commented on pyproject.toml
> +    "gradio>=4.44.0,<5.0",
strongly suggest isolating `gradio` in an elective optional install:

```
[project.optional-dependencies]
web_ui = [
  "gradio>=4.44.0,<5.0"
]
```
then changing the docs to mention that if you want the web ui you do `uv pip install mflux[web_ui]`

`gradio` brings in lots of dependencies.
```sh
pip show gradio
Name: gradio
Version: 4.44.0
...
Requires: aiofiles, anyio, fastapi, ffmpy, gradio-client, httpx, huggingface-hub, importlib-resources, jinja2, markupsafe, matplotlib, numpy, orjson, packaging, pandas, pillow, pydantic, pydub, python-multipart, pyyaml, ruff, semantic-version, tomlkit, typer, typing-extensions, urllib3, uvicorn
```

`pip freeze | wc -l` before `gradio` is 29 packages, *after* is **70** packages, adding *41* requirements to potentially break compatibility with the core functionality of `mflux`, this is a big detriment to software maintenance and supportability, where future users will file Issues to ask why some 2nd degree dependency broke their install

2024-09-23 21:26 UTC, anthonywu commented on src/mflux/ui/gradio/webui.py
> +sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
don't need this

2024-09-23 21:26 UTC, anthonywu commented on src/mflux/ui/gradio/webui.py
> +from mflux.controlnet.flux_controlnet import Flux1Controlnet
these imports have been improved/cleaned up in #55, they should now be available as:

```py
from mflux import (
    Flux1,
    Flux1Controlnet,
    Config,
    ConfigControlnet,
    ModelConfig
)
```

2024-09-23 21:26 UTC, anthonywu commented on src/mflux/ui/gradio/webui.py
> +LORA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "lora")
⏰ this is likely your specific setup @CharafChnioune - should pass the lora path in as an env var `LORA_DIR = os.environ.get("MFLUX_LORA_DIR", None)` where if the default remains `None` then the user just won't get any Lora stuff offered, but should get a UI hint to select the folder path or define the env var upon next try.

`MFLUX_LORA_DIR` - because we want to be specific this dir is for MFlux, and not collide with similar intentioned env vars from other projects.

2024-09-23 21:26 UTC, anthonywu commented on src/mflux/ui/gradio/webui.py
> +    return [f for f in os.listdir(lora_dir) if f.endswith(".safetensors")]
👍🏼

I think this is fine, but there's a newer API for this:

```py
from pathlib import Path

    return list(Path(lora_dir).glob("*.safetensors"))

# OR

   # if the container folder has nested sub dirs with safetensors
   # then can support recursive search
   return list(Path(lora_dir).rglob("*.safetensors"))
```

`rglob` is recommended because I anticipate many LORA downloaders will download container directories, HF/GH repos that are themselves parent directories that nest `.safetensor` artifacts

2024-09-23 21:26 UTC, anthonywu commented on src/mflux/ui/gradio/webui.py
> +        gr.Image("https://raw.githubusercontent.com/CharafChnioune/mflux/main/src/mflux/assets/logo.png", height=100)
should use proper python api to retrieve artifacts already in the package, going to the internet for this is anti-pattern

<img width="959" alt="image" src="https://github.com/user-attachments/assets/c2823e42-c6b5-4ec2-8854-65fb0a8b550a">

using the template above, you should be able to get the image from `mflux.assets` namespace which already contains the image

2024-09-23 21:26 UTC, anthonywu commented on src/mflux/ui/gradio/webui.py
> +                            choices=get_available_lora_files(LORA_DIR), label="Select LoRA Files", multiselect=True
thanks for addressing this concern! 🤝

2024-09-24 01:39 UTC, anthonywu reviewed
I tried the GUI from author's branch. It does not work in the Controlnet flows, the first one I tested. Needs a test plan beyond this PoC.

2024-09-24 01:39 UTC, anthonywu commented on src/mflux/ui/gradio/webui.py
> +LORA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "lora")
confirming this works:

```py
from pathlib import Path

...

LORA_DIR = os.environ.get("MFLUX_LORA_DIR", None)


def get_available_lora_files(lora_dir):
    return [f.name for f in Path(lora_dir).rglob("*.safetensors")]
```

2024-09-24 01:39 UTC, anthonywu commented on src/mflux/ui/gradio/webui.py
> +    lora_paths = [os.path.join(LORA_DIR, f) for f in lora_files] if lora_files else None
all of these should be `lora_paths = lora_files` because `lora_files` is the list from the UI that the user selected, you don't want the list of all the discovered lora files

2024-09-24 01:39 UTC, anthonywu commented on src/mflux/ui/gradio/webui.py
> +            save_canny=save_canny,
this arg has been renamed to `controlnet_save_canny` and `controlnet_save_canny` is not an arg to `ConfigControlnet`, it's an arg to `generate_image`

2024-09-24 01:39 UTC, anthonywu commented on src/mflux/ui/gradio/webui.py
> +    flux = Flux1(
these `flux` objects appear to be scoped in such a way that every "generate image" click would reload the models, while this means we don't have to juggle loading/unloading lora weights and/or caching flux objects, it does mean users pay the model loading cost every click.

something to think about, perf-wise

2024-09-24 16:55 UTC, cocktailpeanut commented
@filipstrand would love to see this incorporated, but if this is not in line with the direction of the project, I'm thinking of directly playing with OP's fork, some guidance would be appreciated! (Although it would be nice to see this integrated into the project since the UI will be up to date with whatever future improvements made to mflux).

2024-09-28 18:51 UTC, closed without merging